/**
 * Roadmap Status Workflow (8 states):
 * 
 * proposed → adr_validated → bdd_pending → bdd_complete → implementing → nfr_validating → complete
 *                                                                      ↘ nfr_blocked
 */
export type RoadmapStatus = 
  | 'proposed' 
  | 'adr_validated' 
  | 'bdd_pending' 
  | 'bdd_complete' 
  | 'implementing' 
  | 'nfr_validating' 
  | 'nfr_blocked' 
  | 'complete';

/**
 * Priority levels for roadmap items
 */
export type Priority = 'high' | 'medium' | 'low';

/**
 * Available view modes for the roadmap dashboard
 */
export type ViewMode = 'kanban' | 'timeline' | 'dependencies';

/**
 * Result of an NFR validation check
 */
export interface NfrResult {
  status: 'pass' | 'fail' | 'pending';
  evidence?: string;
  timestamp?: string;
  validated_by?: string;
  metrics?: Record<string, string | number>;
}

/**
 * ADR compliance check entry
 */
export interface AdrComplianceCheck {
  adr: string;
  compliant: boolean;
  notes?: string;
}

/**
 * Agent approval signature
 */
export interface AgentApproval {
  agent: string;
  timestamp: string;
}

/**
 * BDD test results summary
 */
export interface BddTestResults {
  total: number;
  passed: number;
  failed: number;
  coverage?: string;
}

/**
 * Governance tracking for a roadmap item
 */
export interface Governance {
  adrs: {
    validated: boolean;
    validated_by?: string;
    validated_at?: string;
    compliance_check?: AdrComplianceCheck[];
  };
  bdd: {
    id?: string;
    status: 'draft' | 'approved';
    approved_by?: AgentApproval[];
    test_results?: BddTestResults;
  };
  nfrs: {
    applicable: string[];
    status: 'pending' | 'validating' | 'pass' | 'fail';
    results?: Record<string, NfrResult>;
  };
}

/**
 * A roadmap item with full governance tracking
 */
export interface RoadmapItem {
  id: string;
  title: string;
  status: RoadmapStatus;
  phase?: number;
  priority?: Priority;
  created?: string;
  started?: string;
  completed?: string;
  governance: Governance;
  blocks?: string[];
  depends_on?: string[];
  blocked_by?: string[];
  filePath: string;
}

/**
 * Filter state for the roadmap dashboard
 */
export interface FilterState {
  search: string;
  status: RoadmapStatus | 'all';
  phase: string;
  priority?: Priority | 'all';
  governanceFilter: 'all' | 'adr_pending' | 'bdd_pending' | 'nfr_pending';
}

/**
 * Roadmap data as generated by the plugin
 */
export interface RoadmapData {
  items: RoadmapItem[];
  generatedAt: string;
  validStatuses: RoadmapStatus[];
  validPriorities: Priority[];
}
