import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  dddSidebar: [
    {
      type: 'doc',
      id: 'ddd/index',
      label: 'DDD Overview',
    },
    {
      type: 'doc',
      id: 'ddd/domain-overview',
      label: 'Domain Overview',
    },
    {
      type: 'doc',
      id: 'ddd/bounded-contexts',
      label: 'Bounded Contexts',
    },
    {
      type: 'doc',
      id: 'ddd/ubiquitous-language',
      label: 'Ubiquitous Language',
    },
    {
      type: 'doc',
      id: 'ddd/aggregates-entities',
      label: 'Aggregates & Entities',
    },
    {
      type: 'doc',
      id: 'ddd/value-objects',
      label: 'Value Objects',
    },
    {
      type: 'doc',
      id: 'ddd/domain-events',
      label: 'Domain Events',
    },
    {
      type: 'doc',
      id: 'ddd/use-cases',
      label: 'Use Cases',
    },
    {
      type: 'doc',
      id: 'ddd/context-map',
      label: 'Context Map',
    },
  ],
  bddSidebar: [
    {
      type: 'doc',
      id: 'bdd/index',
      label: 'BDD Overview',
    },
    {
      type: 'doc',
      id: 'bdd/bdd-overview',
      label: 'Methodology',
    },
    {
      type: 'doc',
      id: 'bdd/gherkin-syntax',
      label: 'Gherkin Syntax',
    },
    {
      type: 'doc',
      id: 'bdd/feature-index',
      label: 'Feature Index',
    },
  ],
  agentsSidebar: [
    {
      type: 'doc',
      id: 'agents/index',
      label: 'Agent Overview',
    },
  ],
  roadsSidebar: [
    {
      type: 'doc',
      id: 'roads/index',
      label: 'Roadmap Overview',
    },
    {
      type: 'doc',
      id: 'roads/ROAD-TEMPLATE',
      label: 'Template',
    },
    {
      type: 'category',
      label: 'Phase 0: Foundation',
      items: [
        // Add your road items here
      ],
    },
    {
      type: 'category',
      label: 'Phase 1: Core Features',
      items: [
        // Add your road items here
      ],
    },
  ],
  adrSidebar: [
    {
      type: 'doc',
      id: 'adr/index',
      label: 'ADR Overview',
    },
    {
      type: 'doc',
      id: 'adr/ADR-TEMPLATE',
      label: 'Template',
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        // Add your ADRs here
      ],
    },
    {
      type: 'category',
      label: 'Infrastructure',
      items: [
        // Add your ADRs here
      ],
    },
    {
      type: 'category',
      label: 'Security',
      items: [
        // Add your ADRs here
      ],
    },
  ],
  nfrSidebar: [
    {
      type: 'doc',
      id: 'nfr/index',
      label: 'NFR Overview',
    },
    {
      type: 'doc',
      id: 'nfr/NFR-TEMPLATE',
      label: 'Template',
    },
    {
      type: 'category',
      label: 'Performance',
      items: [
        // Add your NFRs here
      ],
    },
    {
      type: 'category',
      label: 'Security',
      items: [
        // Add your NFRs here
      ],
    },
    {
      type: 'category',
      label: 'Accessibility',
      items: [
        // Add your NFRs here
      ],
    },
  ],
  changesSidebar: [
    {
      type: 'doc',
      id: 'changes/index',
      label: 'Change History',
    },
    {
      type: 'doc',
      id: 'changes/TEMPLATE',
      label: 'Change Template',
    },
    {
      type: 'category',
      label: 'Changes',
      link: {
        type: 'generated-index',
        title: 'All Changes',
        description: 'Complete change history with governance tracking',
        slug: '/changes/all',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'changes',
        },
      ],
    },
  ],
  planningSidebar: [
    {
      type: 'doc',
      id: 'plans/index',
      label: 'Plans Overview',
    },
    {
      type: 'category',
      label: 'Implementation Plans',
      link: {
        type: 'generated-index',
        title: 'Implementation Plans',
        description: 'Detailed implementation plans for features',
        slug: '/plans/all',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'plans',
        },
      ],
    },
  ],
};

export default sidebars;
